route:
  group_by: [ alertname ]
  receiver: 'mail' # default receiver
  repeat_interval: 24h
  routes:
    - receiver: 'teams'
      repeat_interval: 12h
      matchers:
        - severity="medium"

    - receiver: 'teams'
      repeat_interval: 4h
      matchers:
        - severity="high"


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: '${EMAILING_HOST}:${EMAILING_HOST_PORT}'
        auth_username: '${EMAILING_USER}'
        auth_password: '${EMAILING_PASSWORD}'
        from: '${EMAILING_FROM}'
        to: '${EMAILING_TO}'
        require_tls: false

  - name: 'teams'
    webhook_configs:
      - url: "http://prom2teams:8089"
        send_resolved: true