{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cloudiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "openweathermap_cloudiness_percent{location=\"Barcelona\"}",
     "legendFormat": "Cloudiness"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "openweathermap_wind_mph{location=\"Barcelona\"}",
     "legendFormat": "Wind (mph)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "openweathermap_temperature_celsius{location=\"Barcelona\"}",
     "legendFormat": "Temperature ºC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "openweathermap_humidity_percent{location=\"Barcelona\"}",
     "legendFormat": "Humidity (%)"
    }
   ]
  }
 ]
}